#!/bin/bash 
echo "SQL Xaqida Tushuncha"
echo "SQL (Structured Query Language - Strukturalashgan soʻrov tili) — relyatsion maʼlumotlar bazalarini boshqarish, maʼlumotlarni saqlash, yangilash, oʻchirish va qidirish uchun moʻljallangan standart dasturlash tili. SQL jadvallar (satr va ustunlar) bilan ishlaydi va maʼlumotlar bazasi bilan tezkor, ishonchli aloqani taʼminlaydi. Asosiy guruhlari: DDL (tuzilma), DML (manipulyatsiya) va DCL (boshqaruv). "
echo "SQL ning asosiy komponentlari va tushunchalari"
echo "Relyatsion maʼlumotlar bazasi: Maʼlumotlarni jadval koʻrinishida (qator va ustunlar) saqlaydigan tizim"
echo "SQL operatorlar guruhlari:"
echo "DDL (Data Definition Language): Baza obʼektlarini (jadvallar, indekslar) yaratish va oʻzgartirish (CREATE, ALTER, DROP)."
echo "DML (Data Manipulation Language): Maʼlumotlar ustida amallar bajarish (SELECT, INSERT, UPDATE, DELETE)."
echo"DCL (Data Control Language): Maʼlumotlar bazasiga kirish huquqlarini boshqarish (GRANT, REVOKE)."
echo "Asosiy SQL bazalari: PostgreSQL, MySQL, MS SQL Server, Oracle SQL."
echo "Interaktiv va Oʻrnatilgan SQL: Interaktiv SQL soʻrovni darhol bajarib natija bersa, oʻrnatilgan SQL boshqa dasturlash tillari (Java, Pascal) ichida ishlatiladi." 
echo "SQL nimalar uchun ishlatiladi?"
echo "Jadvallardan kerakli maʼlumotlarni filtrlash va tanlab olish."
echo "Yangi maʼlumotlar qoʻshish yoki mavjudlarini yangilash."
echo "Maʼlumotlar bazasi tuzilmasini yaratish va boshqarish"
